package Enumerations;

public enum ProjectApplicationStatus {
    SUCCESS,
    AGE_RESTRICTION_SINGLE,
    FLAT_TYPE_SINGLE,
    AGE_RESTRICTION_MARRIED,
    ELIGIBILITY_UNDETERMINED,
    DUPLICATE_APPLICATION,
    FAILURE
}

